# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: '0 0 * * SAT'
  displayName: Clear docker cache
  branches:
    include:
    - main
  always: true
pr: none
trigger: none

pool:
  name: AksServices

steps:
- script: |
    docker image prune -a --force
    docker builder prune --force
