# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Stop AKS Test
  inputs:
    azureSubscription: 'spn-azure-test-subscription-contributor'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: ''
    # inlineScript: 'az aks stop --name aks-aksservices-test-weu --resource-group rg-aksservices-test-weu'
  
- task: AzureCLI@2
  displayName: Stop AKS Preprod
  inputs:
    azureSubscription: 'spn-azure-preprod-subscription-contributor'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: ''
    # inlineScript: 'az aks stop --name aks-aksservices-preprod-weu --resource-group rg-aksservices-preprod-weu'