# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: AksServices

steps:
- script: |
    docker run --name scan-curity ictu/zap2docker-weekly zap-baseline.py -I -j -t https://identity-dev.carnegie.se -r testreport-api.html -x OWASP-ZAP-Report.xml
    docker cp scan-api:/zap/wrk/ $(Agent.TempDirectory) 
    docker stop scan-curity
    docker container rm scan-curity
  displayName: 'Run a multi-line script'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/Converted-OWASP-ZAP-Report.xml'
    # searchFolder: '$(Build.ArtifactStagingDirectory)/testresults'
    failTaskOnFailedTests: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/wrk'
    artifact: 'owaspresults'
    publishLocation: 'pipeline'